import streamlit as st

from cfo import advisor
from cfo import calculations as calc
from cfo import charts
from cfo import db
from cfo.ui import (
    ACTIONABLE_LEVELS, bulk_calendar_download_button, get_api_key, is_ai_configured, is_dark_theme,
    render_action_items, setup_page, stat_tile,
)


@st.cache_data(ttl=6 * 3600, show_spinner="Generating your CFO briefing...")
def _cached_briefing(snapshot: str, nonce: int, _api_key: str) -> list[dict]:
    return advisor.generate_briefing(_api_key, snapshot)

setup_page("Dashboard")
dark = is_dark_theme()

st.title("Dashboard")
st.caption("A snapshot of where your money stands today.")

accounts = db.list_accounts()
snapshots = db.list_snapshots()
transactions = db.list_transactions()
budgets = db.list_budgets()
debts = db.list_debts()
goals = db.list_goals()

net_worth = calc.net_worth_summary(accounts)
cash_flow = calc.monthly_cash_flow(transactions)
budget_df = calc.budget_vs_actual(budgets, transactions)

latest_income = cash_flow.iloc[-1]["income"] if not cash_flow.empty else 0.0
latest_expenses = cash_flow.iloc[-1]["expenses"] if not cash_flow.empty else 0.0
latest_savings_rate = cash_flow.iloc[-1]["savings_rate"] if not cash_flow.empty else 0.0

col1, col2, col3, col4 = st.columns(4)
with col1:
    stat_tile("Net Worth", f"${net_worth['net_worth']:,.0f}")
with col2:
    stat_tile("This Month's Income", f"${latest_income:,.0f}")
with col3:
    stat_tile("This Month's Expenses", f"${latest_expenses:,.0f}")
with col4:
    stat_tile("Savings Rate", f"{latest_savings_rate:.0%}")

st.divider()
st.subheader("Are you on track?")

health = calc.calculate_health_score(net_worth, cash_flow, budget_df, debts, goals, accounts)
gauge_col, breakdown_col = st.columns([1, 1.4])
with gauge_col:
    st.plotly_chart(charts.health_gauge_chart(health.score, dark=dark), use_container_width=True, config={"displayModeBar": False})
    if health.score is not None:
        st.markdown(f"<div style='text-align:center;font-weight:600;margin-top:-1rem;'>{health.label}</div>", unsafe_allow_html=True)
with breakdown_col:
    if health.components:
        st.caption("What makes up this score:")
        for component in health.components:
            st.progress(component.score / 100, text=f"{component.name} -- {component.score:.0f}%")
            st.caption(component.detail)
    else:
        st.caption("Add accounts, transactions, and goals to calculate your score.")

st.divider()
st.subheader("Your CFO Briefing")

briefing_items: list[dict] = []
if not db.has_any_data():
    st.caption("Once there's data to look at, a proactive briefing will appear here automatically.")
elif not is_ai_configured():
    st.caption(
        "Set up an Anthropic API key in the sidebar to get a proactive, AI-generated briefing here -- "
        "the same idea as Insights below, but reasoning over your whole financial picture instead of "
        "fixed rules, and updated whenever your data changes."
    )
else:
    header_cols = st.columns([5, 1])
    with header_cols[1]:
        if st.button("Regenerate", use_container_width=True):
            st.session_state["briefing_nonce"] = st.session_state.get("briefing_nonce", 0) + 1
    try:
        briefing_items = _cached_briefing(
            advisor.snapshot_json(), st.session_state.get("briefing_nonce", 0), get_api_key()
        )
        render_action_items(briefing_items, key_prefix="briefing")
        st.caption("Generated by Claude from the data on this page -- click Regenerate for a fresh read.")
    except Exception as exc:  # noqa: BLE001 -- surface any API failure without crashing the dashboard
        st.error(f"Couldn't generate a briefing right now: {exc}")

st.divider()

left, right = st.columns([1.3, 1])
with left:
    st.subheader("Net worth trend")
    st.plotly_chart(charts.net_worth_trend_chart(snapshots, dark=dark), use_container_width=True, config={"displayModeBar": False})

    st.subheader("Income vs. expenses")
    st.plotly_chart(charts.income_vs_expenses_chart(cash_flow, dark=dark), use_container_width=True, config={"displayModeBar": False})

with right:
    st.subheader("Spending by category")
    spending = calc.spending_by_category(transactions, month=calc.current_month_key())
    st.plotly_chart(charts.spending_by_category_chart(spending, dark=dark), use_container_width=True, config={"displayModeBar": False})

st.divider()
st.subheader("Insights")
insights = calc.generate_insights(net_worth, cash_flow, budget_df, debts, goals)
render_action_items(insights, key_prefix="insight")

all_actionable = insights + briefing_items
if any(item.get("level") in ACTIONABLE_LEVELS for item in all_actionable):
    st.divider()
    bulk_calendar_download_button(all_actionable, key="bulk_actions")
    st.caption("Bundles every Watch/Action item above into one calendar file.")

if not db.has_any_data():
    st.info("This dashboard is empty. Use **Load sample data** in the sidebar, or start adding your own "
            "accounts, transactions, and debts using the pages in the sidebar.")
